from typing import List, Dict, Any, Optional
import time

try:  # provide a symbol for tests that patch it
    from langchain_community.llms.ollama import Ollama  # type: ignore
except Exception:  # pragma: no cover - optional for tests

    class Ollama:  # dummy placeholder to satisfy patch target
        def __init__(self, *args, **kwargs) -> None:
            pass

        def invoke(self, prompt: str) -> str:  # pragma: no cover - best effort
            return ""


class OllamaProvider:
    """Back-compat shim that talks to langchain Ollama directly for tests."""

    def __init__(self, base_url: Optional[str] = None, model_name: str = "llama2") -> None:
        # Store for potential constructor compatibility; not required by tests due to patching
        self._base_url = base_url
        self._model_name = model_name

    def generate_recommendations(
        self,
        remaining_words: List[str],
        previous_guesses: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        start = time.time()

        # Build a light prompt. Tests patch Ollama.invoke return value, so content isn't critical.
        prompt = (
            "Given remaining words: "
            + ", ".join(remaining_words)
            + ". Suggest four related words as comma-separated values."
        )

        # Instantiate the LLM and get response (module is patched in tests)
        try:
            import importlib

            ollama_mod = importlib.import_module("langchain_community.llms.ollama")
            OllamaCls = getattr(ollama_mod, "Ollama")
            llm = OllamaCls(model=self._model_name)
            raw = llm.invoke(prompt)
        except Exception:
            raw = ""

        # Parse into words
        words = [w.strip() for w in str(raw).split(",") if w.strip()][:4]

        # Map back to original casing if present in remaining_words
        def _map_to_original(items: List[str]) -> List[str]:
            mapped: List[str] = []
            for w in items:
                lw = w.lower()
                found = False
                for orig in remaining_words:
                    if orig.lower() == lw:
                        mapped.append(orig)
                        found = True
                        break
                if not found:
                    mapped.append(w)
            return mapped

        generation_time_ms = int((time.time() - start) * 1000)
        return {
            "recommended_words": _map_to_original(words),
            "connection_explanation": "Generated by Ollama",
            "confidence_score": 0.5,
            "generation_time_ms": generation_time_ms,
        }
